import React, { useState, useEffect } from 'react';
import InputForm from './components/InputForm';
import ResultView from './components/ResultView';
import MatrixBackground from './components/MatrixBackground';
import { UserInput, FullAnalysisResult } from './lib/types';
import { processAnalysis } from './lib/llm';

export default function App() {
  const [result, setResult] = useState<FullAnalysisResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Load from local storage on mount
  useEffect(() => {
    const saved = localStorage.getItem('last_chart_result');
    if (saved) {
      try {
        setResult(JSON.parse(saved));
      } catch (e) { }
    }
  }, []);

  const handleAnalyze = async (input: UserInput) => {
    setLoading(true);
    setError(null);
    try {
      // Direct client-side call instead of API route
      const analysisResult = await processAnalysis(input);

      setResult(analysisResult);
      localStorage.setItem('last_chart_result', JSON.stringify(analysisResult));

    } catch (err: any) {
      console.error(err);
      setError(err.message || "Analysis failed. Please check your API key and try again.");
    } finally {
      setLoading(false);
    }
  };

  const reset = () => {
    setResult(null);
    localStorage.removeItem('last_chart_result');
  };

  return (
    <main className="min-h-screen relative">
      <MatrixBackground />

      {/* Scanning Line Overlay */}
      <div className="fixed inset-0 pointer-events-none z-50 overflow-hidden opacity-[0.03]">
        <div className="w-full h-full bg-[linear-gradient(rgba(18,16,16,0)_50%,rgba(0,0,0,0.25)_50%),linear-gradient(90deg,rgba(255,0,0,0.06),rgba(0,255,0,0.02),rgba(0,0,255,0.06))] bg-[length:100%_2px,3px_100%]"></div>
      </div>

      <div className="relative z-10 p-4 md:p-8">
        {error && (
          <div className="fixed top-4 right-4 bg-red-900/80 text-white p-4 rounded border border-red-500 z-50 shadow-[0_0_20px_rgba(255,0,0,0.3)]">
            {error}
          </div>
        )}

        {!result ? (
          <div className="flex flex-col items-center justify-center min-h-[80vh]">
            <InputForm onSubmit={handleAnalyze} isLoading={loading} />
            <p className="mt-8 text-sm text-primary/40 max-w-md text-center font-mono uppercase tracking-widest">
              Note: Experimental Terminal. The analysis is generated by AI and is for entertainment only.
            </p>
          </div>
        ) : (
          <ResultView result={result} onReset={reset} />
        )}
      </div>
    </main>
  );
}